
using System;
using System.Text;
using System.Collections.Generic;
using ExpertLib;
using System.ComponentModel;

namespace ExpertERP.BusinessEntities
{
    #region GLAccountingImportMapCols
    //-----------------------------------------------------------
    //Generated By: SQLDBTools - LINHCLH (v2.1.44)
    //Class: GLAccountingImportMapColsInfo
    //Created Date: Saturday, 19 Mar 2016
    //-----------------------------------------------------------

    public class GLAccountingImportMapColsInfo : BusinessObject
    {
        public GLAccountingImportMapColsInfo()
        {
        }
        #region Variables
        protected int _gLAccountingImportMapColID;
        [Description("")]
        protected String _gLAccountingImportMapColTableName = String.Empty;
        protected String _gLAccountingImportMapColColumnName = String.Empty;
        protected String _gLAccountingImportMapColMapColumnName = String.Empty;
        protected String _gLAccountingImportMapColSubLedger = String.Empty;
        protected bool _gLAccountingImportMapColCopyCheck = true;
        protected String _gLAccountingImportMapColType = String.Empty;
        protected String _gLAccountingImportMapColCaption = String.Empty;
        protected bool _gLAccountingImportMapColRequiredCheck = true;
        protected bool _gLAccountingImportMapColExsitsCheck = true;
        protected bool _gLAccountingImportMapColNotExsitsCheck = true;
        protected bool _gLAccountingImportMapColFKCheck = true;
        protected bool _gLAccountingImportMapColIsNumberCheck = true;
        protected bool _gLAccountingImportMapColDupplicateCheck = true;
        protected bool _gLAccountingImportMapColIsDateCheck = true;
        protected bool _gLAccountingImportMapColAnalysisCostCheck = true;
        protected String _gLAccountingImportMapColCustomCheck = String.Empty;
        protected String _gLAccountingImportMapColPrimaryColumn = String.Empty;
        protected bool _gLAccountingImportMapColIsLengthCheck = true;
        protected bool _gLAccountingImportMapColIsAccountCheck = true;
        protected bool _gLAccountingImportMapColADConfigValueCheck = true;
        protected bool _gLAccountingImportMapColPrimaryCheck = true;
        protected String _gLAccountingImportMapColCopyDisplayColumnName = String.Empty;
        
        #endregion

        #region Public properties
        public int GLAccountingImportMapColID
        {
            get { return _gLAccountingImportMapColID; }
            set
            {
                if (value != this._gLAccountingImportMapColID)
                {
                    _gLAccountingImportMapColID = value;
                    NotifyChanged("GLAccountingImportMapColID");
                }
            }
        }
        public String GLAccountingImportMapColTableName
        {
            get { return _gLAccountingImportMapColTableName; }
            set
            {
                if (value != this._gLAccountingImportMapColTableName)
                {
                    _gLAccountingImportMapColTableName = value;
                    NotifyChanged("GLAccountingImportMapColTableName");
                }
            }
        }
        public String GLAccountingImportMapColColumnName
        {
            get { return _gLAccountingImportMapColColumnName; }
            set
            {
                if (value != this._gLAccountingImportMapColColumnName)
                {
                    _gLAccountingImportMapColColumnName = value;
                    NotifyChanged("GLAccountingImportMapColColumnName");
                }
            }
        }
        public String GLAccountingImportMapColMapColumnName
        {
            get { return _gLAccountingImportMapColMapColumnName; }
            set
            {
                if (value != this._gLAccountingImportMapColMapColumnName)
                {
                    _gLAccountingImportMapColMapColumnName = value;
                    NotifyChanged("GLAccountingImportMapColMapColumnName");
                }
            }
        }
        public String GLAccountingImportMapColSubLedger
        {
            get { return _gLAccountingImportMapColSubLedger; }
            set
            {
                if (value != this._gLAccountingImportMapColSubLedger)
                {
                    _gLAccountingImportMapColSubLedger = value;
                    NotifyChanged("GLAccountingImportMapColSubLedger");
                }
            }
        }
        public bool GLAccountingImportMapColCopyCheck
        {
            get { return _gLAccountingImportMapColCopyCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColCopyCheck)
                {
                    _gLAccountingImportMapColCopyCheck = value;
                    NotifyChanged("GLAccountingImportMapColCopyCheck");
                }
            }
        }
        public String GLAccountingImportMapColType
        {
            get { return _gLAccountingImportMapColType; }
            set
            {
                if (value != this._gLAccountingImportMapColType)
                {
                    _gLAccountingImportMapColType = value;
                    NotifyChanged("GLAccountingImportMapColType");
                }
            }
        }
        public String GLAccountingImportMapColCaption
        {
            get { return _gLAccountingImportMapColCaption; }
            set
            {
                if (value != this._gLAccountingImportMapColCaption)
                {
                    _gLAccountingImportMapColCaption = value;
                    NotifyChanged("GLAccountingImportMapColCaption");
                }
            }
        }
        public bool GLAccountingImportMapColRequiredCheck
        {
            get { return _gLAccountingImportMapColRequiredCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColRequiredCheck)
                {
                    _gLAccountingImportMapColRequiredCheck = value;
                    NotifyChanged("GLAccountingImportMapColRequiredCheck");
                }
            }
        }
        public bool GLAccountingImportMapColExsitsCheck
        {
            get { return _gLAccountingImportMapColExsitsCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColExsitsCheck)
                {
                    _gLAccountingImportMapColExsitsCheck = value;
                    NotifyChanged("GLAccountingImportMapColExsitsCheck");
                }
            }
        }
        public bool GLAccountingImportMapColNotExsitsCheck
        {
            get { return _gLAccountingImportMapColNotExsitsCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColNotExsitsCheck)
                {
                    _gLAccountingImportMapColNotExsitsCheck = value;
                    NotifyChanged("GLAccountingImportMapColNotExsitsCheck");
                }
            }
        }
        public bool GLAccountingImportMapColFKCheck
        {
            get { return _gLAccountingImportMapColFKCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColFKCheck)
                {
                    _gLAccountingImportMapColFKCheck = value;
                    NotifyChanged("GLAccountingImportMapColFKCheck");
                }
            }
        }
        public bool GLAccountingImportMapColIsNumberCheck
        {
            get { return _gLAccountingImportMapColIsNumberCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColIsNumberCheck)
                {
                    _gLAccountingImportMapColIsNumberCheck = value;
                    NotifyChanged("GLAccountingImportMapColIsNumberCheck");
                }
            }
        }
        public bool GLAccountingImportMapColDupplicateCheck
        {
            get { return _gLAccountingImportMapColDupplicateCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColDupplicateCheck)
                {
                    _gLAccountingImportMapColDupplicateCheck = value;
                    NotifyChanged("GLAccountingImportMapColDupplicateCheck");
                }
            }
        }
        public bool GLAccountingImportMapColIsDateCheck
        {
            get { return _gLAccountingImportMapColIsDateCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColIsDateCheck)
                {
                    _gLAccountingImportMapColIsDateCheck = value;
                    NotifyChanged("GLAccountingImportMapColIsDateCheck");
                }
            }
        }
        public bool GLAccountingImportMapColAnalysisCostCheck
        {
            get { return _gLAccountingImportMapColAnalysisCostCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColAnalysisCostCheck)
                {
                    _gLAccountingImportMapColAnalysisCostCheck = value;
                    NotifyChanged("GLAccountingImportMapColAnalysisCostCheck");
                }
            }
        }
        public String GLAccountingImportMapColCustomCheck
        {
            get { return _gLAccountingImportMapColCustomCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColCustomCheck)
                {
                    _gLAccountingImportMapColCustomCheck = value;
                    NotifyChanged("GLAccountingImportMapColCustomCheck");
                }
            }
        }
        public String GLAccountingImportMapColPrimaryColumn
        {
            get { return _gLAccountingImportMapColPrimaryColumn; }
            set
            {
                if (value != this._gLAccountingImportMapColPrimaryColumn)
                {
                    _gLAccountingImportMapColPrimaryColumn = value;
                    NotifyChanged("GLAccountingImportMapColPrimaryColumn");
                }
            }
        }
        public bool GLAccountingImportMapColIsLengthCheck
        {
            get { return _gLAccountingImportMapColIsLengthCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColIsLengthCheck)
                {
                    _gLAccountingImportMapColIsLengthCheck = value;
                    NotifyChanged("GLAccountingImportMapColIsLengthCheck");
                }
            }
        }
        public bool GLAccountingImportMapColIsAccountCheck
        {
            get { return _gLAccountingImportMapColIsAccountCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColIsAccountCheck)
                {
                    _gLAccountingImportMapColIsAccountCheck = value;
                    NotifyChanged("GLAccountingImportMapColIsAccountCheck");
                }
            }
        }
        public bool GLAccountingImportMapColADConfigValueCheck
        {
            get { return _gLAccountingImportMapColADConfigValueCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColADConfigValueCheck)
                {
                    _gLAccountingImportMapColADConfigValueCheck = value;
                    NotifyChanged("GLAccountingImportMapColADConfigValueCheck");
                }
            }
        }
        public bool GLAccountingImportMapColPrimaryCheck
        {
            get { return _gLAccountingImportMapColPrimaryCheck; }
            set
            {
                if (value != this._gLAccountingImportMapColPrimaryCheck)
                {
                    _gLAccountingImportMapColPrimaryCheck = value;
                    NotifyChanged("GLAccountingImportMapColPrimaryCheck");
                }
            }
        }
        public String GLAccountingImportMapColCopyDisplayColumnName
        {
            get { return _gLAccountingImportMapColCopyDisplayColumnName; }
            set
            {
                if (value != this._gLAccountingImportMapColCopyDisplayColumnName)
                {
                    _gLAccountingImportMapColCopyDisplayColumnName = value;
                    NotifyChanged("GLAccountingImportMapColCopyDisplayColumnName");
                }
            }
        }
        #endregion
    }
    #endregion
}