using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertLib;
namespace ExpertERP.BusinessEntities
{
	#region GLVoucherItems
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:GLVoucherItemsController
	//Created Date:Thursday, January 06, 2011
	//-----------------------------------------------------------
	
	public class GLVoucherItemsController:BaseBusinessController
	{
		public GLVoucherItemsController()
		{
			dal= new DALBaseProvider("GLVoucherItems",typeof(GLVoucherItemsInfo));
		}
    
    }
	#endregion
}