using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using ExpertLib;
namespace ExpertERP.BusinessEntities
{
	#region GLVouchers
	//-----------------------------------------------------------
	//Generated By: Expert Studio
	//Class:GLVouchersController
	//Created Date:Thursday, January 06, 2011
	//-----------------------------------------------------------

    public enum VoucherType
    {
        InPmt = 0,
        OutPmt = 1,
        PmtReq = 2,
        Voucher = 3
    }
	public class GLVouchersController:BaseBusinessController
	{
		public GLVouchersController()
		{
			dal= new DALBaseProvider("GLVouchers",typeof(GLVouchersInfo));
		}

        public void UpdateStatusVoucher(int month, int year, bool isLock)
        {
            string strLock = "";
            if(isLock)
                strLock = "Lock";
            else
                strLock = "New";
            string query = string.Format("UPDATE GLVouchers SET GLVoucherStatusTypeCombo = '{0}' where AAStatus = 'Alive' and MONTH(GLVoucherDate) = '{1}' and YEAR(GLVoucherDate) = N'{2}'",strLock,month,year);
            GMCDbUtil.ExecuteQuery(query);
        }

        
    }
	#endregion
}